name: tapegen
description: Tool for generating tapers, a type-safe encoding for Chest.
version: 0.0.2
repository: https://github.com/chestdb/chest

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  analyzer: ^0.41.1
  build: "1.6.2"
  build_config: ">=0.4.5 <1.0.0"
  chest: # 0.0.4-0
    path: ../chest
  meta: ^1.1.0
  source_gen: ^0.9.0

dev_dependencies:
  build_runner: ^1.11.1
  build_test: ^1.3.6
  extra_pedantic: 1.2.1-nullsafety.0
